version: 2

models:
  - name: stg_weather_city_daily
    columns:
      - name: city_slug
        data_tests:
          - not_null
      - name: observation_date
        data_tests:
          - not_null

  - name: mart_weather_city_daily
    columns:
      - name: observation_date
        data_tests:
          - not_null
      - name: city_slug
        data_tests:
          - not_null
